### Perfil para DOCKER: PostgreSQL via docker-compose

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # Se for usar em producao: primeira vez = create; depois = validate
