### Perfil para DESENVOLVIMENTO: PostgreSQL local

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/consultas_medicas
    username: postgres
    password: ${DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update
