### Perfil para DESENVOLVIMENTO: PostgreSQL

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/consultas_medicas
    username: postgres
    password: 1234
  jpa:
#    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
